# Generated by Django 5.1.1 on 2024-09-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockx',
            name='image',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 39, 6, 369626)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 39, 6, 369626)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 39, 6, 369626)),
        ),
    ]
