# Generated by Django 5.1.1 on 2024-09-09 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl', '0002_stockx_image_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 55, 7, 714664)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 55, 7, 714664)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 21, 55, 7, 714151)),
        ),
        migrations.AlterField(
            model_name='stockx',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
